Consolidated one end point change to fetch all pair related data at once
hashgraph/hedera-accelerator-defi-dex-ui pull request #127
Opened 2023-03-17 10:09 UTC by roshan-bisht-lab49

2023-03-20 15:37 UTC, damiano-melcarne-lab49 requested changes

2023-03-22 18:55 UTC, roshan-bisht-lab49 commented on src/dex-ui/services/JsonRpcService/Pair.ts
> +  const fee = convertEthersBigNumberToBigNumberJS(ethers.BigNumber.from(newResults.pop()));
Done

2023-03-22 18:55 UTC, roshan-bisht-lab49 commented on src/dex-ui/services/JsonRpcService/Pair.ts
> +  const pairObject = pairInfo[0];
Done

2023-03-23 02:04 UTC, damiano-melcarne-lab49 approved these changes

2023-03-23 11:33 UTC, merged