feat/US34370-TA99536: Added the Token Already Associated to wallet error in Token Association Flow
hashgraph/hedera-accelerator-defi-dex-ui pull request #214
Opened 2023-07-27 07:57 UTC by roshan-bisht-lab49

2023-07-27 21:02 UTC, damiano-melcarne-lab49 requested changes

2023-07-27 21:02 UTC, damiano-melcarne-lab49 commented on src/dex-ui/hooks/hederaTokenService/useFetchTokenData.tsx
> +      enabled: !!checkForValidTokenId(tokenId),
Nice guard here 👍

2023-07-28 05:42 UTC, roshan-bisht-lab49 commented on src/dex-ui-components/WalletConnection/WalletTokenAssociation.tsx
> +  const disableAssociateButton = isFetching || isNil(mirrorNodeTokenId) || isLoading || isNotNil(tokenBalance);
Done

2023-07-28 05:42 UTC, roshan-bisht-lab49 commented on src/dex-ui-components/WalletConnection/WalletTokenAssociation.tsx
> +  function isInValidTokenInputField() {
Done

2023-07-28 13:02 UTC, damiano-melcarne-lab49 approved these changes

2023-07-28 13:03 UTC, merged