feat/US34389: Multi Sig Text Proposal
hashgraph/hedera-accelerator-defi-dex-ui pull request #223
Opened 2023-08-07 09:01 UTC by roshan-bisht-lab49

**Added New Multi Sig Text Proposal UI also added new UI for `Link to Discussion`**

<img width="1679" alt="Screenshot 2023-08-07 at 1 31 20 PM" src="https://github.com/hashgraph/hedera-accelerator-defi-dex-ui/assets/89677167/b8c5fca6-e6b0-42fa-9080-238448d9a7aa">
<img width="1680" alt="Screenshot 2023-08-07 at 1 31 29 PM" src="https://github.com/hashgraph/hedera-accelerator-defi-dex-ui/assets/89677167/8589aeb9-24f2-4757-ac6b-539e47be89b8">

**Also added `Link to Discussion` for `GOV` and `NFT` DAO**

<img width="1678" alt="Screenshot 2023-08-07 at 1 54 22 PM" src="https://github.com/hashgraph/hedera-accelerator-defi-dex-ui/assets/89677167/5a72c124-98f0-4f2e-a477-24f7b741548f">

2023-08-07 19:59 UTC, damiano-melcarne-lab49 requested changes
Can be merged after two minor comments are addressed.

2023-08-07 19:59 UTC, damiano-melcarne-lab49 commented on src/dex-ui/pages/dao/CreateADAO/CreateADAOPage.tsx
> +      route: `${Paths.DAOs.absolute}/${Paths.DAOs.Create}/${Paths.DAOs.type}`,
Constants should be capitalized: `Paths.DAOs.type` => `Paths.DAOs.Type`

2023-08-07 19:59 UTC, damiano-melcarne-lab49 commented on src/dex-ui/services/DexService/dao/DAOService.ts
> +      } else if (transactionType === MultiSigProposeTransactionType.TypeSetText) {
Can we quickly refactor this to use switch/case statement?

2023-08-08 04:03 UTC, roshan-bisht-lab49 commented
@damiano-melcarne-lab49  I have addressed the two comments.

2023-08-08 04:03 UTC, merged