Feat/TA99574: Assets List and Deposit Flow for Governance DAO
hashgraph/hedera-accelerator-defi-dex-ui pull request #229
Opened 2023-08-11 14:42 UTC by anshulkhare-lab49

**Description**:
Added the Assets flow for the governance DAO
 - Added the Assets screen for governance DAO
 - Implemented the deposit flow for the governance DAO
 - Updated the token transfer flow for the governance DAO
 
<img width="1536" alt="Screenshot 2023-08-11 at 7 21 18 PM" src="https://github.com/hashgraph/hedera-accelerator-defi-dex-ui/assets/132666177/0ab2375a-bc9e-4955-a6dc-c198410eaf5e">
<img width="1536" alt="Screenshot 2023-08-11 at 7 02 33 PM" src="https://github.com/hashgraph/hedera-accelerator-defi-dex-ui/assets/132666177/3762ba09-adba-4023-af7a-eb28640b7b1f">
<img width="1536" alt="Screenshot 2023-08-11 at 8 05 26 PM" src="https://github.com/hashgraph/hedera-accelerator-defi-dex-ui/assets/132666177/583a7cef-856c-4f82-8da9-fe6f7da183f0">

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-08-14 13:22 UTC, damiano-melcarne-lab49 requested changes

2023-08-14 13:22 UTC, damiano-melcarne-lab49 commented on src/dex-ui/pages/dao/DAOProposals/CreateDAOProposal.tsx
> +          case DAOType.NFT:
Shorthand:

```
case DAOType.NFT:
default:
      return;
```

2023-08-16 13:30 UTC, anshulkhare-lab49 commented on src/dex-ui/pages/dao/DAOProposals/CreateDAOProposal.tsx
> +          case DAOType.NFT:
Done.

2023-08-16 13:35 UTC, damiano-melcarne-lab49 approved these changes

2023-08-16 13:39 UTC, merged