Fix/DAO Upgrade Proposal Enhacemenets
hashgraph/hedera-accelerator-defi-dex-ui pull request #242
Opened 2023-08-25 09:57 UTC by roshan-bisht-lab49

**Optimised the parsing method for DAO upgrade proposals**

2023-08-27 21:24 UTC, damiano-melcarne-lab49 requested changes

2023-08-27 21:24 UTC, damiano-melcarne-lab49 commented on src/dao/hooks/useGovernanceDAOProposals.tsx
>            isAdminApprovalButtonVisible: proposalData?.isAdminApprovalButtonVisible ?? false,
UI state, such as visibility, should be controlled at the component level. Application level `react-query` hooks should be used to fetch/cache/return server state.

2023-08-27 21:24 UTC, damiano-melcarne-lab49 commented on src/dao/hooks/useDAOProposals.tsx
> +  async function getUpgradeProposalData(proposalData: DAOUpgradeProposal) {
Move this function to the service layer (DAO service). This is essentially an API endpoint used for fetching Contract Upgrade Proposal data.

2023-08-27 21:24 UTC, damiano-melcarne-lab49 commented on src/dao/hooks/useDAOProposals.tsx
> +    const parsedProposalDataData = { ...proposalData, proxyAdmin, proxyLogic, currentLogic };
Can be shortened to `parsedProposalData`.

2023-10-17 14:34 UTC, damiano-melcarne-lab49 commented
@roshan-bisht-lab49 Can we close this PR?

2023-10-17 15:02 UTC, closed without merging

2023-10-17 15:02 UTC, roshan-bisht-lab49 commented
> @roshan-bisht-lab49 Can we close this PR?

Yeah I am closing it, I will do it more refactoring.