chore: add maintainers as codeowners to all files
hashgraph/hedera-accelerator-defi-dex-ui pull request #382
Opened 2024-12-10 13:37 UTC by PavelSBorisov

**Description**:
Update CODEOWNERS to provide maintainers ownership of all files in their repos

**Related issue(s)**:

Fixes #381 

**Notes for reviewer**:
N/A

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-12-11 13:44 UTC, web3-nomad approved these changes

2024-12-11 14:10 UTC, rbarkerSL requested changes

2024-12-11 14:10 UTC, rbarkerSL commented on .github/CODEOWNERS
> +/CODEOWNERS                                      @hashgraph/release-engineering-managers @hashgraph/developer-advocates
```suggestion
/CODEOWNERS                                      @hashgraph/release-engineering-managers
```

2024-12-11 14:10 UTC, rbarkerSL commented on .github/CODEOWNERS
> +**/LICENSE                                      @hashgraph/release-engineering-managers @hashgraph/developer-advocates
```suggestion
**/LICENSE                                      @hashgraph/release-engineering-manager
```

2024-12-12 15:12 UTC, rbarkerSL approved these changes

2024-12-12 15:12 UTC, merged